### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by qkum** [HitomaruKonpaku/twspace-crawler#15]
Suggestion.

Add Node 14 install commands to the documentation.

We are thousands of programmers who never used Nodejs before. And it can clearly be done incorrectly.

**Install Node 14:**
```
sudo apt install curl
curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
sudo apt install -y nodejs
```

**Comment by HitomaruKonpaku** [comment]
Hi @qkum , I believe there are many guide for this kind of installation already.

Don't think I need to go into detail 🤔

Anyway I will try to put some link for installation guide.

Thanks!

**Comment by HitomaruKonpaku** [comment]
I just updated README.

Feel free to comment/reopen if you still need something 🤣
