### ISSUE TITLE
How to get data ?

### ISSUE THREAD

**Issue by CreativeSelf0** [HitomaruKonpaku/twspace-crawler#16]
I'm currently trying to test your service. 
I installed the application. However, I tried to simple execute node ./dist/index.js --user myTwitterAccount.
then tried to open twitter space and closed it. But nothing was downloaded nor anything happen any ideas?

**Comment by HitomaruKonpaku** [comment]
@CreativeSelf0 by default script will fetch your tweets (if you not provide any token).

So if you don't tweet about that Space it won't see the Space.

Otherwise it could be related to refresh interval, which by default is 30s

**Comment by CreativeSelf0** [comment]
I want to basically never miss someone I like twitter spaces, In case I miss them i'll have them downloaded. Can I do this?
