### ISSUE TITLE
Unable to monitor users with undescore in the twitter handle

### ISSUE THREAD

**Issue by Tryum** [HitomaruKonpaku/twspace-crawler#18]
Hi,

I noticed that users with undescores are not scanned by the crawler.

I would be happy to help (but not sure how to setup a devenv and how to capture data for unit testing).

Thibault

**Comment by HitomaruKonpaku** [comment]
Hi, I don't think that is the case.

You can check [example config](https://github.com/HitomaruKonpaku/twspace-crawler/blob/master/config.example.json) for more detail.

Also, you can run script with `--debug` to show all the info and paste it here, OR check the logs folder (should be in current working dir /logs, e.g: `/Desktop/logs`)

**Comment by Tryum** [comment]
Ok, thanks !

Well, maybe the issue is something else, but spaces if a friend did not appear.
I'll investigate and keep you in touch.

**Comment by Tryum** [comment]
Issue was not specific to users with underscores in name, I'm still trying to figure out what's happening.
