### ISSUE TITLE
[INFO] Version: 1.11.3

### ISSUE THREAD

**Issue by FevLoad** [HitomaruKonpaku/twspace-crawler#20]
Hello I'm trying to setup the script to monitor users and record spaces without me keep monitoring them myself
so I followed the guide you posted and did this comamnd 
``` twspace-crawler --env ./.env --config ./config.json``` 
all I can see in the log file inside logs folder 
is this 
```
2022-02-22T18:11:40.010Z | [INFO] ================================================================================
2022-02-22T18:11:40.019Z | [INFO] Version: 1.11.3
2022-02-22T18:11:43.370Z | [INFO] ================================================================================
2022-02-22T18:11:43.380Z | [INFO] Version: 1.11.3
2022-02-22T18:11:46.723Z | [INFO] ================================================================================
2022-02-22T18:11:46.732Z | [INFO] Version: 1.11.3
2022-02-22T18:11:50.067Z | [INFO] ================================================================================
2022-02-22T18:11:50.076Z | [INFO] Version: 1.11.3
2022-02-22T18:11:53.411Z | [INFO] ================================================================================
2022-02-22T18:11:53.420Z | [INFO] Version: 1.11.3
2022-02-22T18:11:56.757Z | [INFO] ================================================================================
2022-02-22T18:11:56.766Z | [INFO] Version: 1.11.3
2022-02-22T18:12:00.105Z | [INFO] ================================================================================
2022-02-22T18:12:00.115Z | [INFO] Version: 1.11.3
``` 
so how can I know for sure it's working here

**Comment by HitomaruKonpaku** [comment]
@FevLoad seem like it unable to find the `config.json` file.

Try use absolute path like `c:/config.json`

**Comment by FevLoad** [comment]
I went to the folder and run'ed the script from there 
`2022-02-24T09:04:17.316Z | [DEBUG] Args | {"env":"./.env","config":"./config.json","forceOpen":true}
2022-02-24T09:04:17.318Z | [DEBUG] env.TWITTER_AUTHORIZATION=
2022-02-24T09:04:17.319Z | [DEBUG] env.TWITTER_AUTH_TOKEN=xxxxxxxxxxxxxxxxxxxxxx****
2022-02-24T09:04:20.321Z | [INFO] ================================================================================
2022-02-24T09:04:20.331Z | [INFO] Version: 1.11.3
2022-02-24T09:04:20.689Z | [DEBUG] Args | {"env":"./.env","config":"./config.json","forceOpen":true}
2022-02-24T09:04:20.691Z | [DEBUG] env.TWITTER_AUTHORIZATION=
2022-02-24T09:04:20.692Z | [DEBUG] env.TWITTER_AUTH_TOKEN=xxxxxxxxxxxxxxxxxxxxxx****
2022-02-24T09:04:23.709Z | [INFO] ================================================================================
`

is it now working 
I can confirm the manual monitoring is working fine for me 
if i use --user (users,name,in,here) 
but not this command.

**Comment by HitomaruKonpaku** [comment]
Can you show me your `config` file?

I'm not sure what's going on here since no error 🤔

**Comment by FevLoad** [comment]
> Can you show me your `config` file?
> 
> I'm not sure what's going on here since no error 🤔

@HitomaruKonpaku Here my config file
```css

{
   "interval":10000,
   "users":[
      {
         "Foxxxxxxxxces":"729oxxxxxxCw"
      },
      {
         "dxxxxxxxx":"0hLR1xxxxxxxxxQg"
      },
      {
         "Axxxxx1":"lxfzdyxxxxxxw"
      },
      {
         "axxxxxxy":"so4oxxxxxVYIw"
      },
      {
         "Axxx_68":"Slz2xxxxxxxxxLCg"
      },
          {
         "bxxc":"hxxxxxmMQ"
      },
          {
         "kaxxxxxr":"Ye_xxxxx1BJ5vw"
      },
          {
         "spx24":"yyuxxxxx4nA"
      },
          {
         "m_Axxi76":"lzxxxRPxxx"
      },
          {
         "3xxxx":"EyyxxxxxxFeEyA"
      },
          {
         "NxL":"j7ayCxxxxUL7sxxxA"
      },
          {
         "Nawxxe":"BkxxxxEsrxxxc9-AVi_tNxxx6xvg"
      },
          {
         "at3354defsd7":"Usdfgre4gfrdgfrgAPPSLgA"
      },
          {
         "idvsvvdxcv":"7cUvLexcczzxssxxrRNXNQ"
      },
          {
         "alxzaaa":"4n11wweedfxzzrx26Q"
      },
      {
         "Spssxxxxx":"8OSJxzxzxcdsdfcdsfVUA"
      },
      {
         "Nzzzzz":"ydccccccccccccccccczzzzzwa_Q"
      },
      {
         "spazzzzzzzzz":"z8b,,,,,,hhhhhhhhhh2Fw"
      },
      {
         "_aldddddd":"ISQodLg"
      },
      {
         "napt":"0hLR1"
      },
      {
         "A":"0hL"
      },
      {
         "dba1":"y_Q"
      }
   ],
   "webhooks":{
      "discord":[
         {
            "active":true,
            "urls":[
               "https://discord.com/api/webhooks/xxxxxxxxxxxxxxxxx/thCC2lrpTRxxxxxxxx0tXeTGSL-hzuSxxxxxxxxxxxzWRvOq"
            ],
            "usernames":[
               "all"
            ],
            "mentions":{
               "roleIds":[

               ],
               "userIds":[

               ]
            }
         }
      ]
   }
}
```

please tell me is my discord weebhook seetings is correct?
also do I need to add anything in "usernames" 'all" or leave it like this 
same with mentions field and userids

**Comment by HitomaruKonpaku** [comment]
@FevLoad seem like you messed up config file

Please have a look at `config.example.json`

It should be something like:

```
{
  "interval": 30000,
  "users": [
    {
      "username": "elonmusk"
    },
    {
      "username": "NASA"
    }
  ],
  "webhooks": {
    "discord": [
      {
        "active": true,
        "urls": ["https://discord.com/api/webhooks/***"],
        "usernames": [
          "<all>"
        ],
        "mentions": {
          "roleIds": [],
          "userIds": []
        }
      }
    ]
  }
}
```

The `<all>` indicates that all users will be send to that webhooks

**Comment by FevLoad** [comment]
> ```css
> 
>                ]
>             }
>          }
>       ]
>    }
> }
> ```

Thanks so much for the help.
now it's working as it's should 
just one question, how can I know that discord's weebhook settigs is working or now 


finally 
is it even possible to make the script record space video instead of just audio 
can this be future enhancment or this something can't be done and it's not possible to begin with?

**Comment by HitomaruKonpaku** [comment]
1. To find Spaces, try with https://discover-twitter-spaces.vercel.app
1. What do you mean by `space video` ? It is just audio only

**Comment by FevLoad** [comment]
> 1. To find Spaces, try with https://discover-twitter-spaces.vercel.app
> 2. What do you mean by `space video` ? It is just audio only
Hi there for current/upcoming space I use twitter filter with little editing 
[example](https://twitter.com/search?q=%20filter%3Aspaces%20near%3Ausa&src=typed_query&f=live)

I mean like you do record twitch or other things 
let me show you a link from youtube to demonstate what I'm trying to say.
[click HERE](https://www.youtube.com/watch?v=VpNbJ6Z7zbE) ( Youtube link)

**Comment by HitomaruKonpaku** [comment]
1. Not sure about this, from the beginning I made it to only follow specific users only.
2. No, this is just screen recording and not in scope of this project.

**Comment by FevLoad** [comment]
> 1. Not sure about this, from the beginning I made it to only follow specific users only.
> 2. No, this is just screen recording and not in scope of this project.

Thank you so much mate, I really appreciate your patient and help
you can just answer my last question and close this issue-sort of topic 

how can I make sure that the weebhook for discord is working as it should be and the script is sending notification 
because there's nothing since I put it yesterday/last night.

thanks again.

**Comment by HitomaruKonpaku** [comment]
> how can I make sure that the weebhook for discord is working as it should be and the script is sending notification
because there's nothing since I put it yesterday/last night.

As I said ealier:
1. Find someone who currently have live Space (could be from your [filter](https://twitter.com/search?q=%20filter%3Aspaces%20near%3Ausa&src=typed_query&f=live))
2. Add that username to below config
3. Restart the script

```
{
 "interval": 30000,
 "users": [
   {
     "username": "elonmusk"
   },
   {
     "username": "NASA"
   }
 ],
 "webhooks": {
   "discord": [
     {
       "active": true,
       "urls": ["https://discord.com/api/webhooks/***"],
       "usernames": [
         "<all>"
       ],
       "mentions": {
         "roleIds": [],
         "userIds": []
       }
     }
   ]
 }
}
```

**Comment by FevLoad** [comment]
Thanks so much for the help
All working good now
Thank you again
