### ISSUE TITLE
Selectively download only [Audio] Files

### ISSUE THREAD

**Issue by FevLoad** [HitomaruKonpaku/twspace-crawler#29]
Hello there, 
is it possible to make my script to only Selectively download only [Audio] Files?
I don't need either text chat nor the jsonl file ?

**Comment by HitomaruKonpaku** [comment]
Ok I will prob add a flag to skip it

**Comment by FevLoad** [comment]
Thank You so much 
that would it be Great.

**Comment by HitomaruKonpaku** [comment]
`--skip-download-caption` added
