### ISSUE TITLE
Undefined Space Title

### ISSUE THREAD

**Issue by Infinitay** [HitomaruKonpaku/twspace-crawler#31]
In the Discord webhook, the title of the space is being displayed as `undefined`. This happens when a space does not have a title and therefore no `title` key within the space's data.

See https://github.com/HitomaruKonpaku/twspace-crawler/blob/f1428fcd3127b8114fd429ae743d375b2953498e/src/utils/SpaceUtil.ts#L18

Twitter's front-end sets the space's title in such cases to the display name of the space owner. We could do the same by falling back on 

https://github.com/HitomaruKonpaku/twspace-crawler/blob/f1428fcd3127b8114fd429ae743d375b2953498e/src/utils/SpaceUtil.ts#L26

**Comment by HitomaruKonpaku** [comment]
Hi, I know about this issue and leaving it as `undefined` intentionally (to keep its true value)
