### ISSUE TITLE
Captions 0Kb

### ISSUE THREAD

**Issue by Jojo8275** [HitomaruKonpaku/twspace-crawler#37]
Hey,

since few days all files CC captions are empty... do you know what is the problem ?
Thank you

**Comment by HitomaruKonpaku** [comment]
Yea, I realized it but can not do much since it server responses.

Seem like they changed something, and you can not even see captions of recorded Space.

**Comment by Jojo8275** [comment]
Yes i think it's impossible, it's a new system...
Thank you
