### ISSUE TITLE
NO CAPTIONS

### ISSUE THREAD

**Issue by bcfoo-iscteiulpt** [HitomaruKonpaku/twspace-crawler#38]
As of right now, the script that extracts the captions needs to be fixed. This might be because the JSON from which the captions are usually extracted no longer contains the captions.

**Comment by HitomaruKonpaku** [comment]
Same with #37

**Comment by bcfoo-iscteiulpt** [comment]
That's true.

Could https://github.com/openai/whisper be used to extract text from the audio?

In that case, the challenge would be determining which user each sentence belongs to.
