### ISSUE TITLE
Feature Request: Batch Ended Spaces from Command

### ISSUE THREAD

**Issue by scriggity** [HitomaruKonpaku/twspace-crawler#39]
Would it be possible or is it possible to batch spaces (as I'm not sure how it multithreads, I know its captured more than one space at once for me) or do them as a queue where you could input twspace-crawler --id spaceoneid,spacetwoid,space3id etc. I've been doing them as one offs. And not sure if this is correct.

**Comment by HitomaruKonpaku** [comment]
Hmm not support right now, but doing this will cause some issue with `--url`  🤔

**Comment by scriggity** [comment]
Got it. All good. Thank you. Forgive all my questions. I'll have more I have a lot of interesting ideas of how to use this. Appreciate your efforts.
