### ISSUE TITLE
Feature Request/Question: Stream Isolation

### ISSUE THREAD

**Issue by scriggity** [HitomaruKonpaku/twspace-crawler#40]
Ok another random question. Is it possible since I believe the audio are individual streams from participants to just capture the audio of a single participant - like if i wanted to record my own space and isolate my own voice for sampling/cuts without others talking over me? Sometimes I want to do subclips but someone talks over or buries something I said and I want to just pull my or one other persons audio for editing.

**Comment by HitomaruKonpaku** [comment]
This is not possible since we only have 1 data stream from Twitter.

**Comment by scriggity** [comment]
Got it. Thank you.
