### ISSUE TITLE
Request failed with status code 403

### ISSUE THREAD

**Issue by Rettich82** [HitomaruKonpaku/twspace-crawler#48]
Hi, I get this error:

[ERROR] [UserManager] getUsersByUsernames: Request failed with status code 403 | {"requestId":"667a0f54-c312-4e81-91b5-67792c142147","response":{"data":{"client_id":"27283493","detail":"When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal.","registration_url":"https://developer.twitter.com/en/docs/projects/overview","title":"Client Forbidden","required_enrollment":"Appropriate Level of API Access","reason":"client-not-enrolled","type":"https://api.twitter.com/2/problems/client-forbidden"}}}

The error started today. It worked before and I tried to use a new project.

**Comment by HitomaruKonpaku** [comment]
Seem like since 2023-06-09, Twitter deactive all token that not valid

You can try disable `TWITTER_AUTHORIZATION` and use `TWITTER_AUTH_TOKEN` instead

**Comment by Rettich82** [comment]
Works, thanks!

**Comment by scriggity** [comment]
Sorry to be a pain and pile on here. I changed the .env by commenting out the TWITTER_AUTHORIZATION and enabled the TWITTER_AUTH_TOKEN does that still use the bearer token? yah? once i swapped that i dont get the 403 error. but now i AM getting [UserListWatcher] getSpaces: Maximum number of redirects exceeded | {"requestId":"f1195fd9-f74c-4ede-a221-875dd27577fd","response":{}}

And I apologize I'm just not API savvy enough to figure out how to fix this. Trying to learn but hours spent googling and fiddling with auth keys and checking my json file and I still can't get it working.

**Comment by HitomaruKonpaku** [comment]
@scriggity Hi

`TWITTER_AUTH_TOKEN` can be obtain from your twitter session

1. Sign in to Twittetr, and follow below steps
2. Press F12 to open dev tool
3. Click on `Application` > `Cookies`
4. Copy `auth_token`

![image](https://github.com/HitomaruKonpaku/twspace-crawler/assets/9608105/417b3a85-348b-4551-a85d-330b5418c48b)

**Comment by scriggity** [comment]
Oh man, thanks mate. I've learned so much from this project. Appreciate it. This is really my first attempt at playing with api's and code. Obvious right? I've learned a lot and really appreciate your time and attention to comments. Thank you so much.
