### ISSUE TITLE
New @ tracking system

### ISSUE THREAD

**Issue by Jojo8275** [HitomaruKonpaku/twspace-crawler#50]
Since yesterday I noticed on my Raspberry that the @ followed in the config.json work even when they are not host of the spaces (before the @ had to be the host of the space to trigger the capture), on the other hand on my PC the system has not changed, it only captures if the @ starts the space.
Do you know why ?

ps: FYI I prefer the new @ tracking system (capturing the space even if the @ doesn't host it).
I'm on 1.11.13 on Raspberry and PC.

Thank you

**Comment by HitomaruKonpaku** [comment]
I believe it can track Space of following user that is host/admin/speaker.
