### ISSUE TITLE
after the new update got some issues i cant fix it myself

### ISSUE THREAD

**Issue by tcssh211065** [HitomaruKonpaku/twspace-crawler#52]
i start the twspace crawler and it only print the message like this ,please help 
2023-07-01T08:33:20.986Z | [ERROR] [UserManager] getUserByScreenName: Invalid value "undefined" for header "x-csrf-token" | {"username":"achan_UGA"}

**Comment by Jojo8275** [comment]
TWITTER_AUTH_TOKEN=
TWITTER_CSRF_TOKEN=

in your .env

**Comment by HitomaruKonpaku** [comment]
Please check installation guide

**Comment by tcssh211065** [comment]
i check it and i change for new .env and still not working

**Comment by HitomaruKonpaku** [comment]
@tcssh211065 try to run with `--env <path_to_env_file>`

**Comment by Jojo8275** [comment]
i think your TWITTER_AUTH_TOKEN is different if you had a old TWITTER_AUTH_TOKEN on your .env
check please in your cookies (google chrome, edge or another...)

**Comment by tcssh211065** [comment]
> 

thank you its working

**Comment by tcssh211065** [comment]
run with --env <path_to_env_file>
