### ISSUE TITLE
Space Downloading

### ISSUE THREAD

**Issue by Cowticket** [HitomaruKonpaku/twspace-crawler#53]
I am quite upset about what Qelon has done to Twitter. I used to be able to download spaces but I am no longer able. I wanted this to work, I went through and followed the instructions for setup. Is it just me, or are there truly issues? When I initiate a space download I am met with this: getSpaceMetadata: Invalid value "undefined" for header "x-csrf-token" | {"requestId" Any help would be appreciated. Thank you kindly.

**Comment by HitomaruKonpaku** [comment]
@Cowticket Please check [installation](https://github.com/HitomaruKonpaku/twspace-crawler/blob/master/INSTALLATION.md#unofficial-api) again

You have to have `.env` file, and use `--env` to provide env path

Or quick run

```
 TWITTER_AUTH_TOKEN=xxx TWITTER_CSRF_TOKEN=xxx twspace-crawler -d --id 1YqxoApBQMQGv
```

**Comment by Cowticket** [comment]
Thank you. I got that working. I have one more question. What is the best way to convert the JSONL files to JSON or Excel. Do you have a script or advice for that. I appreciate your help!

**Comment by HitomaruKonpaku** [comment]
JSONL is just a simple text file with multiple json string, 1 json per line

For converting you can try google it.

**Comment by Cowticket** [comment]
Ive had it working for a little bit now I am receiving Request failed with status code 429 when it loads the user list. What does this mean? Is there a limit to how many I can have? A time out period? Sorry bud.

**Comment by Rettich82** [comment]
Same here. Seems to be a new bug.

**Comment by Cowticket** [comment]
> Same here. Seems to be a new bug.

Thank you for the reply.

**Comment by Jojo8275** [comment]
Same here too... @HitomaruKonpaku do you know what is the new problem ? :)
Thank you

**Comment by HitomaruKonpaku** [comment]
Update & try again i guess

**Comment by Jojo8275** [comment]
It's ok now since upgrade...
What was the api limit before 50req/15min ? 

Thank you @HitomaruKonpaku

**Comment by Cowticket** [comment]
Did the update, I still gives me etSpaces: Request failed with status code 401. Am I missing something?

**Comment by Jojo8275** [comment]
401 it's because your auth_token is bad... you need to upload the good token

**Comment by HitomaruKonpaku** [comment]
@Jojo8275 iirc it was 500req/15mins, now 50req/15mins
