### ISSUE TITLE
no longer supported

### ISSUE THREAD

**Issue by lhs55502002** [HitomaruKonpaku/twspace-crawler#65]
Can't install it.

<img width="867" alt="屏幕截图 2023-08-22 115816" src="https://github.com/HitomaruKonpaku/twspace-crawler/assets/62332619/029d8c6c-9b37-4969-ad0c-cc47ec0d4592">

**Comment by NitsuSaiNeko** [comment]
Just installed it for the first time and is working on my side.
Is your Node.js updated?

**Comment by witchfindertr** [comment]
node -v
v18.17.0
