### ISSUE TITLE
Unexpected token '.' in Util.js

### ISSUE THREAD

**Issue by jiatern** [HitomaruKonpaku/twspace-crawler#7]
Hi, thanks for making this tool, I am giving it a try but encountered the following error on both Windows and Ubuntu:
![image](https://user-images.githubusercontent.com/8150437/143985075-13404f77-c394-4a70-9e50-a044e2d237d5.png)

I tried with --user, --config or --id, all result in the same error.

**Comment by HitomaruKonpaku** [comment]
Which node version did you use?

[Optional chaining (?.)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) require node v14

**Comment by jiatern** [comment]
> Which node version did you use?
> 
> [Optional chaining (?.)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) require node v14

Hi, thanks for your reply, I upgraded my node and it works now. One more question, when using `--user` or `--id` with a live spaces running, it seems to just monitor the spaces but not downloading. I suppose it will download after the spaces ends, but it doesn't.

It is stuck at `[INFO] [SpaceWatcher@1OwxWzgpxxxxxx] Playlist url: https://prod-fastly....` indefinitely. I could use `--force` to force download while the stream is still live but it will not download the complete spaces until the end.

Did I use it correctly?

**Comment by HitomaruKonpaku** [comment]
Hi @jiatern the script actually wait for space to end before process download (not live download)

You can try to run with `--debug` to see more detail (or check logs in `/logs` dir

**Comment by trumad** [comment]
I also don't seem to get any output. There's a .media folder, with a m4a of the first 6 seconds of the twitter space, and a small amount of generated subtitles.

For now, I'm using this command to download the audio:

`ffmpeg -i PlaylistURL -c copy output.ts`

My logfiles show this kind of info. Nothing seems wrong. There's just no file output.

`2021-12-04T16:13:56.336Z | [DEBUG] [SpaceWatcher@1vOGwyzZaDrxB] Status: 200
2021-12-04T16:13:56.337Z | [DEBUG] [SpaceWatcher@1vOGwyzZaDrxB] Found chunks: 32,33,34
2021-12-04T16:13:56.337Z | [DEBUG] [SpaceWatcher@1vOGwyzZaDrxB] Recheck dynamic playlist in 10000ms
2021-12-04T16:14:05.833Z | [DEBUG] [UserWatcher@trumad] Space count: 1
2021-12-04T16:14:05.834Z | [DEBUG] [UserWatcher@trumad] Space ids: 1vOGwyzZaDrxB
2021-12-04T16:14:06.338Z | [DEBUG] [SpaceWatcher@1vOGwyzZaDrxB] Checking dynamic playlist | {"url":"https://prod-fastly-eu-west-3.video.pscp.tv/Transcoding/v1/hls/VLlet4yHmG1QcyjXXx4UOiG884buw5I88SDArHwOXIAehD4btoJlByXdXMD_moITogqdTODidN5l3nHtM0VQ1w/non_transcode/eu-west-3/periscope-replay-direct-prod-eu-west-3-public/audio-space/dynamic_playlist.m3u8?type=live"}
2021-12-04T16:14:06.415Z | [DEBUG] [SpaceWatcher@1vOGwyzZaDrxB] Status: 200
2021-12-04T16:14:06.416Z | [DEBUG] [SpaceWatcher@1vOGwyzZaDrxB] Found chunks: 35,36,37
2021-12-04T16:14:06.417Z | [DEBUG] [SpaceWatcher@1vOGwyzZaDrxB] Recheck dynamic playlist in 10000ms
2021-12-04T16:14:16.427Z | [DEBUG] [SpaceWatcher@1vOGwyzZaDrxB] Checking dynamic playlist | {"url":"https://prod-fastly-eu-west-3.video.pscp.tv/Transcoding/v1/hls/VLlet4yHmG1QcyjXXx4UOiG884buw5I88SDArHwOXIAehD4btoJlByXdXMD_moITogqdTODidN5l3nHtM0VQ1w/non_transcode/eu-west-3/periscope-replay-direct-prod-eu-west-3-public/audio-space/dynamic_playlist.m3u8?type=live"}
2021-12-04T16:14:16.533Z | [DEBUG] [SpaceWatcher@1vOGwyzZaDrxB] Status: 200
2021-12-04T16:14:16.534Z | [DEBUG] [SpaceWatcher@1vOGwyzZaDrxB] Found chunks: 38,39,40,41
2021-12-04T16:14:16.534Z | [DEBUG] [SpaceWatcher@1vOGwyzZaDrxB] Recheck dynamic playlist in 10000ms
2021-12-04T16:14:26.545Z | [DEBUG] [SpaceWatcher@1vOGwyzZaDrxB] Checking dynamic playlist | {"url":"https://prod-fastly-eu-west-3.video.pscp.tv/Transcoding/v1/hls/VLlet4yHmG1QcyjXXx4UOiG884buw5I88SDArHwOXIAehD4btoJlByXdXMD_moITogqdTODidN5l3nHtM0VQ1w/non_transcode/eu-west-3/periscope-replay-direct-prod-eu-west-3-public/audio-space/dynamic_playlist.m3u8?type=live"}
2021-12-04T16:14:26.611Z | [DEBUG] [SpaceWatcher@1vOGwyzZaDrxB] Status: 200
2021-12-04T16:14:26.612Z | [DEBUG] [SpaceWatcher@1vOGwyzZaDrxB] Found chunks: 42,43,44
2021-12-04T16:14:26.613Z | [DEBUG] [SpaceWatcher@1vOGwyzZaDrxB] Recheck dynamic playlist in 10000ms
2021-12-04T16:14:36.551Z | [DEBUG] [UserWatcher@trumad] Space count: 1
2021-12-04T16:14:36.552Z | [DEBUG] [UserWatcher@trumad] Space ids: 1vOGwyzZaDrxB
2021-12-04T16:14:36.614Z | [DEBUG] [SpaceWatcher@1vOGwyzZaDrxB] Checking dynamic playlist | {"url":"https://prod-fastly-eu-west-3.video.pscp.tv/Transcoding/v1/hls/VLlet4yHmG1QcyjXXx4UOiG884buw5I88SDArHwOXIAehD4btoJlByXdXMD_moITogqdTODidN5l3nHtM0VQ1w/non_transcode/eu-west-3/periscope-replay-direct-prod-eu-west-3-public/audio-space/dynamic_playlist.m3u8?type=live"}`

**Comment by trumad** [comment]
Perhaps I was being impatient. It seems to have worked as expected. the audio file ended up in the .media directory after the space ended. Nice to have the peace of mind of manually grabbing the stream with ffmpeg at the same time though.

The only remaining issue is that the captions didn't download this time round. They have worked before. This is the only error:

`2021-12-05T02:27:22.375Z | [ERROR] [SpaceCaptionsDownloader@1djGXPzpLwzGZ] socket hang up
`

If this happens again for another Space recording, I'll open a separate issue.

Thank you for making this tool!

**Comment by HitomaruKonpaku** [comment]
Hi @trumad, glad to see it worked for you.

About the captions, script will try to download if exist but in case of unexpected error you can manually retry download captions with command

```
node ./dist/index.js cc d 1djGXPzpLwzGZ <chat_access_token>
```

Also remember to update to v1.5.1 :D

**Comment by jiatern** [comment]
Mine also works now, pairing with `--user` it successfully monitored the spaces and eventually downloaded after the spaces ended. It definitely took quite some time after the spaces ended to initiate the download process, but it works, including the caption.

There's one line of error after downloading captions though: 
```
...
[INFO] [SpaceCaptionsExtractor] Captions saved to /home/bin/twspace-crawler/.media/twitterusername/[20211205] twitterusername (1OwxWzgdPEMJQ) CC.txt
[ERROR] [UserWatcher@twitterusername] Cannot read properties of undefined (reading 'data')
```

Even though it doesn't affect the downloading, but I need to Ctrl+C to end the script.

Thanks for making this awesome tool!

**Comment by HitomaruKonpaku** [comment]
@jiatern The purpose of `--user` is to let the script monitor user(s) indefinitely.

And the error above seem like something with server response, thanks for the report.

**Comment by trumad** [comment]
> ```
> node ./dist/index.js cc d 1djGXPzpLwzGZ <chat_access_token>
> ```

Thanks so much. I'm afraid I can't find the access token in any of the output or the all.log file. I searched "access" and "token" but couldn't find any matches. Where should I look for this?

**Comment by trumad** [comment]
Sorry - i found it. The space went across midnight, so it's in the previous day's all.log file!

I'm still getting the socket error. Full logs:

`2021-12-05T09:46:19.141Z | [INFO] [SpaceCaptionsDownloader@1djGXPzpLwzGZ] Downloading captions to 211205094619 (1djGXPzpLwzGZ) CC.jsonl
2021-12-05T09:46:19.147Z | [INFO] [SpaceCaptionsDownloader@1djGXPzpLwzGZ] Downloading part 1
2021-12-05T09:46:30.177Z | [ERROR] [SpaceCaptionsDownloader@1djGXPzpLwzGZ] socket hang up`

The resulting 211205094619 (1djGXPzpLwzGZ) CC.jsonl file is empty.

Is it unwise to post my access token here, assuming you'd even want to track down this issue at all?

**Comment by HitomaruKonpaku** [comment]
@trumad Can you find and post this data for me? Chat access token should be public so you are safe

```[DEBUG] [SpaceWatcher@1rmxPgjNYRmJN] accessChat data | {"subscriber":"","publisher":"","auth_token":"-","signer_key":"MIIBPzCB7qADAgECAhBLhqKc1s1aS1ZJIrtd5ckJMAoGCCqGSM49BAMCMBcxFTATBgNVBAoTDFBlcmlzY29wZSBDbzAeFw0xNjA0MjIxOTQ2MjFaFw0xNjA1MjIxOTQ2MjFaMBcxFTATBgNVBAoTDFBlcmlzY29wZSBDbzBOMBAGByqGSM49AgEGBSuBBAAhAzoABOAmaz/KpIDJiw1x2HYjvZY9HsLyttPOPBJcEjiOK35Id1pTjmnLwqq8YX97+bKzGqRnN4WJETWfoycwJTAOBgNVHQ8BAf8EBAMCAqQwEwYDVR0lBAwwCgYIKwYBBQUHAwEwCgYIKoZIzj0EAwIDQAAwPQIdANIbJvIiiBVkvIUBKg2RpEp1xzuoL1DAD5fcy60CHGptu/TYVpNIdcVfqtMhd2uc8RfmvJA/TgKI4mw=","signer_token":"-","channel":"-","should_verify_signature":false,"access_token":"24-i-nOZJxZoNHDsXhSytE4_XLJniW2fnfqD3O00HuNFuU4ChqNsbOM7aHlMAD6IkIRHqHSWrI7kCsXqwNBnsDYBqHAIinFUSHHlEZcFIfVSefG11mk2SElu5LD3qPgyr1MyOIR0rIQXHpeNQzDT0_n9cIeXDQjO69iD4zfExtAYS-7Hw2QiHs9ZUqeLTFZkiLJp-6TlwciEbu5yoFiLiLw1ZqjLMaOnvngFeIJWN6yZmEFLYvuSEtTqnP2E-0Vnihgs4N5cgqp5d2PBBF9Jg7xBKETzilQ9-AWmAIWv7-k1JqoFQLuKkYdFj8rcK98jbhI3zDUKpvtu6GKGv5lyXACyGT56uGfFhFcA1nz8LWE8q6tsLOloOsMSuENDt7LuZHmaL16o","endpoint":"https://prod-chatman-ancillary-ap-northeast-1.pscp.tv","replay_access_token":"2jlyIWHMoHqjj7nxrRwUMtrjaEdUdfMgKQ000GdzNwnbx0DzU9f8HjPl1T-Nc7qg-6exv8c2GA58jmHF2S93Utzw22rJxtjVozFuz4hvMnvHZ1WnNMTcbPmakMP-yn2O9YQ5U5P3p0Aip5ITEvCwTIjeWGG3kYT2eXqn4QGJ95jjt6CbJ2anGu3nUXwPnxrEpXELuHrBZrGmflN1nPTySxXznGNnc_8B9AfF7Vg1JXbvp-OUw_iK9ReSqPMLT-DpLsjr0VAS2eBUTZm9g9EyES49WeylwRTQXpQ","replay_endpoint":"https://chatman-replay-ap-northeast-1.pscp.tv","room_id":"1rmxPgjNYRmJN","participant_index":0,"read_only":true,"should_log":false,"chan_perms":{"pb":0,"cm":15}}```

**Comment by trumad** [comment]
Thank you so much for your prompt help:

`2021-12-04T21:46:21.055Z | [DEBUG] [SpaceWatcher@1djGXPzpLwzGZ] accessChat data | {"subscriber":"","publisher":"","auth_token":"-","signer_key":"MIIBPzCB7qADAgECAhBLhqKc1s1aS1ZJIrtd5ckJMAoGCCqGSM49BAMCMBcxFTATBgNVBAoTDFBlcmlzY29wZSBDbzAeFw0xNjA0MjIxOTQ2MjFaFw0xNjA1MjIxOTQ2MjFaMBcxFTATBgNVBAoTDFBlcmlzY29wZSBDbzBOMBAGByqGSM49AgEGBSuBBAAhAzoABOAmaz/KpIDJiw1x2HYjvZY9HsLyttPOPBJcEjiOK35Id1pTjmnLwqq8YX97+bKzGqRnN4WJETWfoycwJTAOBgNVHQ8BAf8EBAMCAqQwEwYDVR0lBAwwCgYIKwYBBQUHAwEwCgYIKoZIzj0EAwIDQAAwPQIdANIbJvIiiBVkvIUBKg2RpEp1xzuoL1DAD5fcy60CHGptu/TYVpNIdcVfqtMhd2uc8RfmvJA/TgKI4mw=","signer_token":"-","channel":"-","should_verify_signature":false,"access_token":"25RYTbKeOGA8Rpcy3X350yBQi0t6NjOUQsQ2bABv1Hc7Irm91_5TxhCVdnDCNby2N8ne-xkDZuMQcBF_4gN6mx4lHwdsV6sO44ST7yQLcRX6S_4oirKKCLiKySy1IEmGgzSVjO_aCja1JUJlJkiVeoFEFO1bdTTwOaX7sGPr2kYdVvIV_4A7_MP8uSNgnAtHISmaQRHzxqZFuEmPlHdVpur15jRKqpi9cpwpawWSO2x0vAXkdkBySFdYq71UXlAJVSokvl-1fNnBJ16MXNNCXKRCC7_n6-SVK4u9aEZXCk2sIv7OCbld-_jJR3f7rCifh-lcZSS8K2Ld-WphyeCkUf4WEyodRKIdF8HZ7a6MDprPfoCKkgFt1UvgXQwf8QJGfb3oR","endpoint":"https://prod-chatman-ancillary-eu-central-1.pscp.tv","replay_access_token":"2A3cJI6VyJr_-LGZiIQT7QE-otnjYQ6nmcQAUxB1oOXM_A5G4FU9gT_B4m3ZcUhimHnct5qaC3-OJq3YH7LAyRKAqDKpAx09cSXiQwLXx8hl0ufd316pDpQM6lXe6S5zTkJ480SIykZ4cD9Q5vnMBfeoINN01h9BcxHlNByn8Kagzc8d9NH94EZ_f7lE-sTf4GRyMsIH3THhjO04Z471hiA3vAuwRs35zdYz9z9DMfqp0y3avzFoZQ4Fb8a62I4yhWqxU7rbX08prXGFvDthkT6CZ0Q6vnD0","replay_endpoint":"https://chatman-replay-eu-central-1.pscp.tv","room_id":"1djGXPzpLwzGZ","participant_index":0,"read_only":true,"should_log":false,"chan_perms":{"pb":0,"cm":15}}`

**Comment by HitomaruKonpaku** [comment]
@trumad Seem like endpoint need to change

 Can you update with new version and try below command

```node ./dist/index.js --debug cc d 1djGXPzpLwzGZ https://prod-chatman-ancillary-eu-central-1.pscp.tv 25RYTbKeOGA8Rpcy3X350yBQi0t6NjOUQsQ2bABv1Hc7Irm91_5TxhCVdnDCNby2N8ne-xkDZuMQcBF_4gN6mx4lHwdsV6sO44ST7yQLcRX6S_4oirKKCLiKySy1IEmGgzSVjO_aCja1JUJlJkiVeoFEFO1bdTTwOaX7sGPr2kYdVvIV_4A7_MP8uSNgnAtHISmaQRHzxqZFuEmPlHdVpur15jRKqpi9cpwpawWSO2x0vAXkdkBySFdYq71UXlAJVSokvl-1fNnBJ16MXNNCXKRCC7_n6-SVK4u9aEZXCk2sIv7OCbld-_jJR3f7rCifh-lcZSS8K2Ld-WphyeCkUf4WEyodRKIdF8HZ7a6MDprPfoCKkgFt1UvgXQwf8QJGfb3oR```

I got `connect ETIMEDOUT` most of the time prob because live too far from EU

**Comment by trumad** [comment]
Thank you. I reinstalled from scratch just in case, but I'm seeing the same issue unfortunately. 

`2021-12-05T13:43:40.265Z | [INFO] [SpaceCaptionsDownloader@1djGXPzpLwzGZ] Downloading captions to 211205134340 (1djGXPzpLwzGZ) CC.jsonl
2021-12-05T13:43:40.272Z | [INFO] [SpaceCaptionsDownloader@1djGXPzpLwzGZ] Downloading chunk 1
2021-12-05T13:43:50.482Z | [ERROR] [SpaceCaptionsDownloader@1djGXPzpLwzGZ] socket hang up
`

**Comment by HitomaruKonpaku** [comment]
@trumad I update new code (`1.5.3`) and it now able to download this.

Can you check if the file is good?

[211205134945 (1djGXPzpLwzGZ) CC.txt](https://github.com/HitomaruKonpaku/twspace-crawler/files/7656109/211205134945.1djGXPzpLwzGZ.CC.txt)

**Comment by trumad** [comment]
Yes, it's perfect! Thank you very much! And the functionality is working as expected. I love the way it auto-retries if a chunk fails to download. Hopefully I've helped to make this tool even more robust.

**Comment by HitomaruKonpaku** [comment]
@trumad Thanks! 😁

@jiatern All your problem solved, I guess?

**Comment by jiatern** [comment]
> @jiatern All your problem solved, I guess?

@HitomaruKonpaku yes my problems are solved now, thank you!
