### ISSUE TITLE
Watching user failded when the user is hosting a living space

### ISSUE THREAD

**Issue by Neo-101** [HitomaruKonpaku/twspace-crawler#72]
Thanks for the project. When I find a twitter user is hosting a space,  I simply use "--user" command to test. However, it seems could not find the living space but keeps failing to request a previous space which is finished long time ago.

> neo@vultr:~/twitter_space$ twspace-crawler --user Paris13Jeanne
> 2023-12-12T15:01:21.728Z | [INFO] ================================================================================
> 2023-12-12T15:01:21.731Z | [INFO] Version: 1.12.9
> 2023-12-12T15:01:22.040Z | [INFO] Starting in user mode | {"userCount":1,"users":["Paris13Jeanne"]}
> 2023-12-12T15:01:22.533Z | [INFO] [UserWatcher@Paris13Jeanne] Watching...
> 2023-12-12T15:01:24.377Z | [ERROR] [UserWatcher@Paris13Jeanne] getAudioSpaceById: Request failed with status code 404 | {"id":"1ypKddBEmEpKW"}
> 2023-12-12T15:01:56.074Z | [ERROR] [UserWatcher@Paris13Jeanne] getAudioSpaceById: Request failed with status code 404 | {"id":"1ypKddBEmEpKW"}
> 2023-12-12T15:02:27.648Z | [ERROR] [UserWatcher@Paris13Jeanne] getAudioSpaceById: Request failed with status code 404 | {"id":"1ypKddBEmEpKW"}

**Comment by HitomaruKonpaku** [comment]
See https://github.com/HitomaruKonpaku/twspace-crawler/issues/73#issuecomment-1852537814

**Comment by Neo-101** [comment]
> See [#73 (comment)](https://github.com/HitomaruKonpaku/twspace-crawler/issues/73#issuecomment-1852537814)

It worked. Thank you very much.
