### ISSUE TITLE
--id option failed

### ISSUE THREAD

**Issue by Neo-101** [HitomaruKonpaku/twspace-crawler#73]
Thanks for the project. I failed with --id option: 

> neo@vultr:~/twitter_space$ twspace-crawler --id 1ypKddBEmEpKW
> 2023-12-12T15:15:15.026Z | [INFO] ================================================================================
> 2023-12-12T15:15:15.029Z | [INFO] Version: 1.12.9
> 2023-12-12T15:15:15.340Z | [INFO] Starting in space id mode | {"id":"1ypKddBEmEpKW"}
> 2023-12-12T15:15:15.341Z | [INFO] [SpaceWatcher@1ypKddBEmEpKW] Watching...
> 2023-12-12T15:15:15.341Z | [INFO] [SpaceWatcher@1ypKddBEmEpKW] Space url: https://twitter.com/i/spaces/1ypKddBEmEpKW
> 2023-12-12T15:15:15.356Z | [ERROR] [SpaceWatcher@1ypKddBEmEpKW] getAudioSpaceById: Cannot read properties of undefined (reading 'config')
> 2023-12-12T15:15:15.584Z | [ERROR] [SpaceWatcher@1ypKddBEmEpKW] getAudioSpaceByRestId: Request failed with status code 404
> 2023-12-12T15:15:15.585Z | [ERROR] [SpaceWatcher@1ypKddBEmEpKW] AudioSpace metadata not found
> 2023-12-12T15:15:15.586Z | [INFO] [SpaceWatcher@1ypKddBEmEpKW] Retry watch in 10000ms

**Comment by HitomaruKonpaku** [comment]
@Neo-101 

See [here](https://github.com/HitomaruKonpaku/twspace-crawler/blob/master/INSTALLATION.md#unofficial-api)

You need to run with `--env`

**Comment by Neo-101** [comment]
> @Neo-101
> 
> See [here](https://github.com/HitomaruKonpaku/twspace-crawler/blob/master/INSTALLATION.md#unofficial-api)
> 
> You need to run with `--env`

It worked. Thank you very much.
