### ISSUE TITLE
Transcription cc.txt

### ISSUE THREAD

**Issue by Jojo8275** [HitomaruKonpaku/twspace-crawler#75]
hello, 
you must have noticed that the subtitles file generally remains empty at 0kb. to get the cc you have to go to the Space and activate it via the ... "activate subtitles" from there this unlocks the problem for the current Space. is it possible via the code to modify it so that the api asks the cc to activate without needing to do it on Space? THANKS

**Comment by Jojo8275** [comment]
@HitomaruKonpaku

**Comment by Jojo8275** [comment]
You didn't understand what I said...

I said that the CC can be retrieved without problem currently provided that you physically go to the space via the Twitter application and activate the live subtitles in the space, from there the transcription is also activated for the .txt file.

My question was to know if we cannot directly activate the subtitles via the API to avoid having to go to the space on Twitter to activate it via the application...

THANKS

**Comment by HitomaruKonpaku** [comment]
> My question was to know if we cannot directly activate the subtitles via the API to avoid having to go to the space on Twitter to activate it via the application...

What do you mean...?

**Comment by Jojo8275** [comment]
@HitomaruKonpaku 

last year via the API we could retrieve the subtitles without any problem before Twitter changed its code. Since the API code change, we no longer retrieve subtitles automatically. 

I found a solution to retrieve the subtitles from spaces but it requires going to the Twitter application, launching spaces and activating the subtitles. as soon as you activate the subtitles via the application this is also not found via the API. 

For example, if I arrive at the end of 02:03 of Space and I launch the subtitles via the Twitter application, as soon as the Space is finished I will have all the subtitles from 02:03 in the recovered txt file via API. My question is whether we cannot directly activate the subtitles via the API as was the case last year.

thank you

**Comment by HitomaruKonpaku** [comment]
> My question is whether we cannot directly **activate the subtitles via the API** as was the case last year.

What do you mean by "activate the subtitles via the API** ?

It is currently download all available transcription.
