### ISSUE TITLE
Monitor without downloading? 

### ISSUE THREAD

**Issue by qwertyuiop97** [HitomaruKonpaku/twspace-crawler#82]
is there any way to set it up so that it can monitor when a certain profile goes live with a space but instead of downloading it just gets that m3u8 dynamic url and space information but skips the download?

My line of thinking is that I don't want to download every single space but I do want to have the dynamic url m3u8 link in case I decide to download it later.

**Comment by HitomaruKonpaku** [comment]
@qwertyuiop97 seem to be easy 🤔 

Lemme add some more params to the app

**Comment by qwertyuiop97** [comment]
Okay thanks! I have another question, is it possible to download the captions from a space that has ended using the one time download command? The .txt file seems to be getting downloaded only when the spaces are being monitored per user.

When i use the command for the one-time download and give both space id and dynamic url, I don't get the captions .txt file.

**Comment by HitomaruKonpaku** [comment]
If space is recorded, you can download entire thing normally
If not, check logs to get chat acccess token and run the `cc` command

**Comment by qwertyuiop97** [comment]
What would i search for in the log files? I searched for "token" "chat" and "access" and didn't find anything that looked like the the access token.

I downloaded the space using space id and dynamic url.

**Comment by HitomaruKonpaku** [comment]
Something like this
![image](https://github.com/user-attachments/assets/edbaa5c1-165b-4933-8309-dc771bcccbee)

> I downloaded the space using space id and dynamic url.

Which likely space not archive so cant help unless you find the chat token in logs during monitoring

**Comment by HitomaruKonpaku** [comment]
If you download "recorded" space without providing dynamic url, it will auto extract the chat info and download
